import 'package:flutter/foundation.dart';
import '../models/player_model.dart';
import '../repositories/player_repository.dart';

/// Provider manages player state and notifies UI of changes
/// ChangeNotifier = tells Flutter to rebuild widgets when data changes
class PlayerProvider extends ChangeNotifier {
  final PlayerRepository _repository = PlayerRepository();

  // State variables
  List<Player> _players = [];           // All players
  Player? _selectedPlayer;              // Currently selected player
  bool _isLoading = false;              // Loading indicator
  String? _errorMessage;                // Error message to show user

  // Getters - expose state to UI (read-only)
  List<Player> get players => _players;
  Player? get selectedPlayer => _selectedPlayer;
  bool get isLoading => _isLoading;
  String? get errorMessage => _errorMessage;
  bool get hasPlayers => _players.isNotEmpty;

  /// Fetch all players from database
  Future<void> fetchPlayers() async {
    _setLoading(true);
    _clearError();

    try {
      _players = await _repository.getAllPlayers();
      print('✅ Loaded ${_players.length} players');
      notifyListeners(); // Tell UI to rebuild
    } catch (e) {
      _setError('Failed to load players: $e');
      print('❌ Error in fetchPlayers: $e');
    } finally {
      _setLoading(false);
    }
  }

  /// Search players by name
  Future<void> searchPlayers(String query) async {
    if (query.isEmpty) {
      await fetchPlayers(); // If search is empty, show all
      return;
    }

    _setLoading(true);
    _clearError();

    try {
      _players = await _repository.searchPlayers(query);
      notifyListeners();
    } catch (e) {
      _setError('Search failed: $e');
    } finally {
      _setLoading(false);
    }
  }

  /// Filter players by position
  Future<void> filterByPosition(String position) async {
    _setLoading(true);
    _clearError();

    try {
      _players = await _repository.getPlayersByPosition(position);
      notifyListeners();
    } catch (e) {
      _setError('Filter failed: $e');
    } finally {
      _setLoading(false);
    }
  }

  /// Select a player (for viewing details)
  Future<void> selectPlayer(String playerId) async {
    _setLoading(true);
    _clearError();

    try {
      _selectedPlayer = await _repository.getPlayerById(playerId);
      notifyListeners();
    } catch (e) {
      _setError('Failed to load player: $e');
    } finally {
      _setLoading(false);
    }
  }

  /// Create new player
  Future<bool> createPlayer({
    required String name,
    required int age,
    required int heightCm,
    required int weightKg,
    String? position,
  }) async {
    _setLoading(true);
    _clearError();

    try {
      // Create temporary player object (id will be generated by Supabase)
      final newPlayer = Player(
        id: '', // Will be replaced by Supabase
        name: name,
        age: age,
        heightCm: heightCm,
        weightKg: weightKg,
        position: position,
        createdAt: DateTime.now(),
      );

      final createdPlayer = await _repository.createPlayer(newPlayer);
      
      // Add to local list
      _players.add(createdPlayer);
      _players.sort((a, b) => a.name.compareTo(b.name)); // Keep sorted
      
      notifyListeners();
      return true; // Success
    } catch (e) {
      _setError('Failed to create player: $e');
      return false; // Failure
    } finally {
      _setLoading(false);
    }
  }

  /// Update existing player
  Future<bool> updatePlayer(Player player) async {
    _setLoading(true);
    _clearError();

    try {
      final updatedPlayer = await _repository.updatePlayer(player);
      
      // Update in local list
      final index = _players.indexWhere((p) => p.id == updatedPlayer.id);
      if (index != -1) {
        _players[index] = updatedPlayer;
        _players.sort((a, b) => a.name.compareTo(b.name));
      }

      // Update selected player if it's the same one
      if (_selectedPlayer?.id == updatedPlayer.id) {
        _selectedPlayer = updatedPlayer;
      }

      notifyListeners();
      return true;
    } catch (e) {
      _setError('Failed to update player: $e');
      return false;
    } finally {
      _setLoading(false);
    }
  }

  /// Delete player
  Future<bool> deletePlayer(String playerId) async {
    _setLoading(true);
    _clearError();

    try {
      await _repository.deletePlayer(playerId);
      
      // Remove from local list
      _players.removeWhere((p) => p.id == playerId);
      
      // Clear selected if it was deleted
      if (_selectedPlayer?.id == playerId) {
        _selectedPlayer = null;
      }

      notifyListeners();
      return true;
    } catch (e) {
      _setError('Failed to delete player: $e');
      return false;
    } finally {
      _setLoading(false);
    }
  }

  /// Clear selected player
  void clearSelection() {
    _selectedPlayer = null;
    notifyListeners();
  }

  /// Get player by ID from local list (no database call)
  Player? getPlayerById(String playerId) {
    try {
      return _players.firstWhere((p) => p.id == playerId);
    } catch (e) {
      return null;
    }
  }

  // Private helper methods
  void _setLoading(bool value) {
    _isLoading = value;
    notifyListeners();
  }

  void _setError(String message) {
    _errorMessage = message;
    notifyListeners();
  }

  void _clearError() {
    _errorMessage = null;
  }
}
